### ISSUE TITLE
Robot Design

### ISSUE THREAD

**Issue by tomtzook** [Flash3388/Flash2024#7]
Come up with specific systems and components that make up the robot. This is generally decided by strategy team and the all group, however, we are interested in the the design from a programming perspective., i.e.
- what each system can do
- what it is composed of
- what sensors we can and should use,
- what automations are possible,
- how will the drivers control and operate the robot

Use this issue to document thoughts, ideas, desires and such. We will use this as a reference.

**Comment by tomtzook** [comment]
Pneumatic systems expected

**Comment by tomtzook** [comment]
Two prototypes in work:
- Arm with shooter and collector
- Separate shooter and collector
- Climber thingy for the chain. With possibly, the ability to move along the chain.

**Comment by tomtzook** [comment]
@Maayan-Luzon  @NoamZW learn more about the prototypes, we need to see what we would want to require from the robot.

**Comment by tomtzook** [comment]
- Design for the shooter-collector system inspired by [this](https://www.youtube.com/watch?v=iOz55ATplok)
  - we want to use an absolute encoder for positioning of the arm portion of the system to detect its position. @Maayan-Luzon  and @NoamZW  check specific model from Ido.
  - freedom of firing position, so we can shoot from different positions. Interpolation for firing based on angle, motor speed and distance to target. Or another mathematics model.
  - @Maayan-Luzon and @NoamZW  check which motors are used for what parts of the system.
  - IR reflective, break sensor (color sensor v3) to detect note being collected.
  - @tomtzook read more on mathematical models for firing

**Comment by tomtzook** [comment]
Experiment with collection of notes with different positioning and orientation to see if the collector is able to easily collect them, or if more work is required.
@NoamZW suggested: We may want to use vision to find the note and collect with it. 
@Maayan-Luzon: check about purchasing another limelight.

**Comment by Maayan-Luzon** [comment]
I have asked about the systems: 
### Intake System:
- one neo 550 motor
- SparkMax controller
- should spin in constant voltage and have the possibility to spin both ways (in case we would want to release the note we collected).

### Shotter System:
- two neo 500 motors.
- two SparkMax controllers (master and follower).
- the shotting speed should be constant so we need to use PID to make sure we at the right speed.
- the system need to have high speed for the "speaker" and low speed for the "amp". 

### Arm System:
- two neo 500 motors
- two SparkMax controllers (master and follower).
- absolute encoder connected to the DIO in the roborio.
- two micro-switches in each side to make sure we won't crush the system on the robot ;)

**Comment by tomtzook** [comment]
@Maayan-Luzon please expand on:

> two micro-switches in each side to make sure we won't crush the system on the robot ;)

Are they touch microswitches? are they weird as limit switches to the SparkMAX as hardware limit switch, or are they software limit switch?

What actions should be written for each system? Start with driver manual actions and then expend on it with auto actions.

**Comment by Maayan-Luzon** [comment]
Ido told me that the switches will be from the same kind we talked about before. Those that wired to the SparkMAXs as hardware limit switch. Personally, I don't know how to use them so I would appreciate it if you (@tomtzook ) would explain about them. 

Additionally, the intake system will contain a distance sensor that is linked to the DIO and will indicate whether or not we have collected anything with a true or false response. 

Regarding the actions, I had hoped that we would talk about them together, but I suppose I can provide some examples of what the systems should be capable of. 
Pressing a button will initiate the intake system. A separate actions are required to remove a note from the system and to take it in. The system must be able to function autonomously if we wish to do so. 

When we order the shooter (a button or other object) to fire, it must do so at a constant velocity. In order to ensure that the shooter is moving at the proper speed, we must use a PID controller. Also, this system has to "know" how to function alone.

The arm is a system designed to function nearly entirely on its own. The arm can be moved to a specific angle by pressing a button, which is determined by a function dependent on the target's distance from us.

**Comment by tomtzook** [comment]
@Maayan-Luzon 
For _SparkMax_ hardware limit switches, see: 
- https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#getForwardLimitSwitch(com.revrobotics.SparkLimitSwitch.Type)
- https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#getReverseLimitSwitch(com.revrobotics.SparkLimitSwitch.Type)
- https://codedocs.revrobotics.com/java/com/revrobotics/sparklimitswitch
- https://github.com/REVrobotics/SPARK-MAX-Examples/blob/master/Java/Limit%20Switch/src/main/java/frc/robot/Robot.java
